.nh
.TH alert_syslog.sh 5 "July 2025" alert_syslog.sh "User Manual"

.SH NAME
alert_syslog.sh \- Sample Syslog alert agent for pacemaker with filtering


.SH SYNOPSIS
pcs alert create id=alert_cluster  \\
 path=\fB/var/lib/pacemaker/alert_syslog.sh\fP  options \\
 \fBRHA_syslog_facility\fP=local2 \fBRHA_syslog_priority\fP=err \\
 \fBRHA_syslog_tag\fP=SERVICEGROUP \fBRHA_alert_server\fP=syslog.example.com


.SH DESCRIPTION
\fBalert_syslog.sh\fP provides a means to filter pacemaker syslog alerts at the
 source and direct them to the desired syslog server without having to tweak
 your syslog or rsyslog configuration on the cluster nodes.

.PP
Filtering, syslog target, facility, priority, and syslog tag are all driven by
 variables which are set by PCS alert options


.SH OPTIONS
\fBpath=\fP_/var/lib/pacemaker/alert\fIsyslog.sh\fP

.PP
This is the path to the alert agent on the nodes' filesystems - the path
 should match to wherever you've installed the file. By default they're placed
 in /usr/share/pacemaker/alerts/ when installing from rpm, and they're usually
 manually placed in /var/lib/pacemaker/ for runtime when the agents are
 configured.

.PP
\fBRHA_syslog_facility=\fP\fIfacility\fP

.PP
This is in relation to the the syslog alert facility (man 3 syslog)

.PP
Syslog \fIfacility\fP Examples:

.PP
LOG_AUTH, AUTHPRIV, LOG_LOCAL0, local5, etc.
  LOCAL0 - LOCAL7 are for custom use, for alerting mechanisms such as
  this script

.PP
\fBRHA_syslog_priority=\fP_RHA_syslog\fIpriority\fP

.PP
This is in relation to the syslog priority level (man 3 syslog)

.PP
Syslog \fIpriority\fP examples:
 LOG_EMERG, LOG_ALERT, LOG_CRIT, ERR, WARNING, NOTICE, INFO, DEBUG

.PP
(there are more facilities and levels than included above)

.PP
If you've worked with syslog.conf files before you'll recall it's normal for
 the facility to be specified in all lower case, and the LOG_ prefix to be
 dropped. So these examples would be typical:

.PP
local2.*    /var/log/pacemaker/syslog # Capture ALL notices sent to LOG_LOCAL2
 to /var/log/pacemaker/syslog

.PP
local2.err  /var/log/pacemaker/errorlog # capture all notices of ERR or
 greater priority to /var/log/paceemaker/errorlog

.PP
\fBRHA_syslog_tag=\fP\fItag\fP

.PP
This is in relation to the syslog \fItag\fP level (\fIman 5 rsyslog.conf, man 1 logger\fP)

.PP
This is the syslog "tag" attribute which is supported by many aggreggators,
 useful for additional filtering

.PP
\fBRHA_syslog_port=\fP\fIport\fP

.PP
This is the port the syslog aggregator is listening on if it's anything other
 than the standard syslog port of \fI514\fP

.PP
\fBRHA_syslog_proto=\fP\fIprotocol\fP

.PP
This is the protocol syslog is listening for; valid values are \fItcp\fP or \fIudp\fP

.PP
\fBRHA_alert_kind=\fP\fI"fencing,node,resource"\fP

.PP
This option sets the RHA_alert_kind variable in the alert_syslog alert
 agent, to specify the criteria on which alerts to allow to send to the email
 recipient.

.PP
Note that otherwise-unspecified alert types will be sent to the recipient
 regardless of the filter specification.

.PP
\fIfencing\fP

.PP
These alerts are generated when a node is fenced, whether automatically or
 automatically.

.PP
\fInode\fP

.PP
These alerts when a node is suspended, unsuspended, rebooted, joins the
 cluster, etc.

.PP
\fIresource\fP

.PP
These alerts are generated when a resource is started, stopped, or fails to
 start.


.SH INSTALLATION
Place alert_syslog.sh in pacemaker lib dirctory (typically /var/lib/pacemaker/)
 chown it the pacemaker user and group (typically hacluster:haclient on a
 default install); chmod it 0750

.EX
[root@nodea ~]# cp /usr/share/pacemaker/alerts/alert_syslog.sh.sample \\
  /var/lib/pacemaker/alart_syslog.sh
[root@nodea ~]# chown hacluster:haclient /var/lib/pacemaker/alert_syslog.sh
[root@nodea ~]# chmod 0750 /var/lib/pacemaker/alert_syslog.sh
.EE

.PP
Proceed to EXAMPLES section for alert configuration


.SH EXAMPLES
Example which sends all alerts:

.EX
~] # pcs alert create id=alert_webcluster1 path=/var/lib/pacemaker/alert_syslog.sh
 options RHA_syslog_facility=local2 RHA_syslog_priority=err \\
 RHA_syslog_tag=webcluster1 RHA_alert_server=fqdn.syslog.example.com
.EE

.PP
Example which sends only fencing and unhandled alerts:

.EX
~] # pcs alert create id=alert_webcluster1 path=/var/lib/pacemaker/alert_syslog.sh
 options RHA_syslog_facility=local2 RHA_syslog_priority=err \\
 RHA_syslog_tag=webcluster1 RHA_alert_server=fqdn.syslog.example.com \\
 RHA_alert_kind="fencing"
.EE

.PP
This example will send alerts of kind node, resource, and "unhandled"
 alerts, but not fencing notifications:

.EX
~] # pcs alert create id=alert_webcluster1 path=/var/lib/pacemaker/alert_syslog.sh \\
 options RHA_syslog_facility=local2 RHA_syslog_priority=err \\
 RHA_syslog_tag=webcluster1 RHA_alert_server=fqdn.syslog.example.com \\
 RHA_alert_kind="node,resource"
.EE


.SH HISTORY
July 2025, Originally compiled by Kimberly Lazarski (klazarsk@redhat.com)
